### ISSUE TITLE
Õmg thầy oi mí bạn oi cíuuuu🥺

### ISSUE THREAD

**Issue by GiaHan06** [GiaHan06/Lop-10A02-Nhom-02#12]
Ũa cái câu 4 bài 6 é “trình bày hoàn thiện đầy đủ các bước giải bài toán trên máy tính” là shao zị😢

**Comment by LTGHan** [comment]
H-hong biết nữa :'(

**Comment by GiaHan06** [comment]
> H-hong biết nữa :'(
Đim nai Hân hok ngũ😌

**Comment by GiaHan06** [comment]
Chắc khók quá chưa làm toán nữa :<

**Comment by HuynhLeBaoTran** [comment]
hu heo tui cx ko biec nx:((

**Comment by GiaHan06** [comment]
> hu heo tui cx ko biec nx:((

dao don qua troi oi

**Comment by NguyenNgocQuynhAnh** [comment]
bài 6 tui thấy có 5 bước để giải bài toán

**Comment by NguyenNgocQuynhAnh** [comment]
bước 1 là cái gì mà xác định rõ thành phần input output với mối quan hệ giữa hai cái đó để lựa thuật toán với ngôn ngữ lập trình

**Comment by NguyenNgocQuynhAnh** [comment]
lý thuyết là z chứ hok bíc ghi gì -))

**Comment by NguyenNgocQuynhAnh** [comment]
bước 3 viết chương trình là tổ chức dữ liệu với chọn ngôn ngữ lập trình

**Comment by NguyenNgocQuynhAnh** [comment]
tui nghĩ chắc bước 3 giống cái pascal hồi đó học nhma hok bíc làm sao :>

**Comment by NguyenNgocQuynhAnh** [comment]
xong cái bước 3 thì qua bước 4 hiệu chỉnh, kiểu như là mấy bà nhập input a b c zo rồi thì mấy bà thế số zo á

**Comment by NguyenNgocQuynhAnh** [comment]
vd như mấy bà nhập a=3 b=4 c=5 z  đóa

**Comment by NguyenNgocQuynhAnh** [comment]
bước cuối là viết tài liệu, đọc trên mạng thì thấy nó bảo là mô tả lại mấy cái bước mình làm

**Comment by NguyenNgocQuynhAnh** [comment]
mô tả lại từ bước 2 đến 4 á (mô tả, chương trình mà mình viết với cái kết quá, tức là cái phần thế số)

**Comment by NguyenNgocQuynhAnh** [comment]
gòy đó, nói z thoai chứ làm thì hok bíc làm :))

**Comment by GiaHan06** [comment]
@LTGHan zô xem nè :)) tutu na tui đang load

**Comment by GiaHan06** [comment]
> gòy đó, nói z thoai chứ làm thì hok bíc làm :))

để tui load cái đã hmu hmu :'(

**Comment by NguyenNgocQuynhAnh** [comment]
hình như tui có gán link á, hai bà zo coi thử chứ tui cũng hok hiểu tui nói gì =))

**Comment by GiaHan06** [comment]
> hình như tui có gán link á, hai bà zo coi thử chứ tui cũng hok hiểu tui nói gì =))

ulatroi nghe đao quá :((

**Comment by GiaHan06** [comment]
https://www.canva.com/design/DAEvPmUHkXY/s64dSp2v7H25SfUUUENsdg/view?utm_content=DAEvPmUHkXY&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
ulatroi xong được 1 cái rùi nè, bất tỉnh khoảng chừng 2s :'( zô xem đi cạ nhà iu, chỗ nào hok ỗn thì nói tui nha mai tui sửa chứ h tui xĩu ròi

**Comment by HuynhLeBaoTran** [comment]
Ỏ đỉn qa nè chùi đất uii

**Comment by HuynhLeBaoTran** [comment]
Nhúm trửn vất vả rùi^^

**Comment by GiaHan06** [comment]
> Nhúm trửn vất vả rùi^^

Hê hê ngại 🙄👉👈

**Comment by GiaHan06** [comment]
@HienCaoPhuNhuan ũa thầy oii, cái câu 4 vế sau là shao con chưa hỉu á thầy, làm giống QAnh nói hã thầy??

**Comment by HienCaoPhuNhuan** [comment]
> @HienCaoPhuNhuan ũa thầy oii, cái câu 4 vế sau là shao con chưa hỉu á thầy, làm giống QAnh nói hã thầy??

Có thể tóm tắt lại khum thầy lười đọc

**Comment by GiaHan06** [comment]
> Có thể tóm tắt lại khum thầy lười đọc

chắc là giống mấy cái bước trong sách á thầy, bước 1: xác định bài toán; bước 2: lựa chọn hoặc thiết kế thuật toán...

**Comment by GiaHan06** [comment]
Thay dung lang im den the....
Vi lang im se dit tret con tym😔💔

**Comment by HienCaoPhuNhuan** [comment]
> Thay dung lang im den the....
> Vi lang im se dit tret con tym😔💔

Đúng rồi, làm như vậy á
